---
driver:
  name: docker
  privileged: true
  use_sudo: false

  # binary: /usr/local/bin/docker
  run_command: /sbin/init
  provision_command:
    - mkdir -p /var/run/sshd

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
    - recipe[test::default]
  - name: system
    run_list:
    - recipe[paramount::system]
  - name: security
    run_list:
    - recipe[paramount::security]
  - name: cloud
    run_list:
    - recipe[test::cloud]
  - name: email
    run_list:
    - recipe[test::email]
  - name: multimedia
    run_list:
    - recipe[test::multimedia]
  - name: web
    run_list:
    - recipe[test::web]
