---
driver:
  name: docker
  use_sudo: false
  privileged: true
  binary: /usr/local/bin/docker
  run_command: /sbin/init
  provision_command:
    - mkdir -p /var/run/sshd
  cachier: true
  customize:
    memory: 4096

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.9.41
  log_level: info
  file_atomic_update: false
  environments_path: test/integration/environments
  data_bags_path: test/fixtures/data_bags
  attributes:
    openssh:
      server:
        permit_root_login: 'yes'
    authorization:
      sudo:
        users: ['vagrant']
        passwordless: true

platforms:
  - name: ubuntu-14.04
    image: ubuntu-upstart:14.04
    run_list:
      - recipe[apt]
  - name: ubuntu-16.04
    run_list:
      - recipe[apt]
  # - name: debian-7.8
  #   run_list:
  #     - recipe[apt]
  # - name: fedora-23
  #   run_list:
  #     - recipe[yum]
  # - name: centos-7.3
  #   run_list:
  #     - recipe[yum]

suites:
  - name: default
    run_list:
    - recipe[test::default]
  - name: cloud
    run_list:
    - recipe[test::cloud]
  - name: email
    run_list:
    - recipe[test::email]
  - name: multimedia
    run_list:
    - recipe[test::multimedia]
  - name: web
    run_list:
    - recipe[test::web]
