---
driver:
  name: vagrant
  use_sudo: false
  cachier: true
  customize:
    memory: 2048

driver_config:
  require_chef_omnibus: 12.9.41

provisioner:
  require_chef_omnibus: true
  name: chef_zero
  deprecations_as_errors: true
  log_level: info
  environments_path: test/integration/environments
  data_bags_path: test/fixtures/data_bags
  attributes:
    openssh:
      server:
        permit_root_login: 'yes'
    authorization:
      sudo:
        users: ['vagrant']
        passwordless: true

platforms:
  - name: ubuntu-16.04
    driver_config:
      box: bento/ubuntu-16.04
    run_list:
      - recipe[apt]
  - name: debian-8.6
    run_list:
      - recipe[apt]
  - name: fedora-25
    run_list:
      - recipe[yum]
  - name: centos-7.3
    run_list:
      - recipe[yum]

suites:
  - name: default
    run_list:
    - recipe[test::default]
  - name: cloud
    run_list:
    - recipe[test::cloud]
  - name: email
    run_list:
    - recipe[test::email]
  - name: multimedia
    run_list:
    - recipe[test::multimedia]
  - name: web
    run_list:
    - recipe[test::web]
