---
driver:
  name: vagrant
  use_sudo: false
  network:
    - ['forwarded_port', {guest:  80, host: 8080, auto_correct: true}]
    - ['forwarded_port', {guest: 443, host: 8443, auto_correct: true}]
  cachier: true
  customize:
    memory: 4096

verifier:
  name: inspec

provisioner:
  name: chef_zero
  product_name: chef
  product_version: <%= ENV['CHEF_VERSION'] || 'latest' %>
  install_strategy: once
  log_level: info
  file_atomic_update: false
  environments_path: test/integration/environments
  data_bags_path: test/fixtures/data_bags
  attributes:
    postfix:
      recipient_canonical_map_entries:
        john: john@example.com
    openssh:
      server:
        permit_root_login: 'yes'
    authorization:
      sudo:
        users: ['vagrant', 'kitchen']
        passwordless: true

platforms:
  - name: amazonlinux
    run_list: yum-epel::default
    driver_config:
      box: mvbcoding/awslinux
  - name: centos-6
    run_list: yum-epel::default
  - name: centos-7
    run_list: yum-epel::default
  - name: debian-8
    run_list: apt::default
  - name: debian-9
    run_list: apt::default
  - name: fedora-27
  - name: freebsd-10
  - name: freebsd-11
  - name: opensuse-leap-42
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-16.04
    run_list: apt::default

suites:
  - name: default
    run_list:
    - recipe[test::default]
    attributes:
      paramount:
      - disable_cloud: true
      - disable_email: true
      - disable_multimedia: true
      - disable_web: true
  - name: cloud
    run_list:
    - recipe[test::cloud]
  - name: email
    run_list:
    - recipe[test::email]
  - name: multimedia
    run_list:
    - recipe[test::multimedia]
  - name: security
    run_list:
    - recipe[test::security]
  - name: system
    run_list:
    - recipe[test::system]
  - name: web
    run_list:
    - recipe[test::web]
