---
driver:
  name: vagrant
  use_sudo: false
  network:
    - ["forwarded_port", {guest:  80, host: 8080, auto_correct: true}]
    - ["forwarded_port", {guest: 443, host: 8443, auto_correct: true}]
  cachier: true
  customize:
    memory: 4096

provisioner:
  name: chef_zero
  product_name: chef
  product_version: <%= ENV['CHEF_VERSION'] || 'latest' %>
  install_strategy: once
  log_level: info
  file_atomic_update: false
  environments_path: test/integration/environments
  data_bags_path: test/fixtures/data_bags
  attributes:
    postfix:
      recipient_canonical_map_entries:
        john: john@example.com
    openssh:
      server:
        permit_root_login: 'yes'
    authorization:
      sudo:
        users: ['vagrant', 'kitchen']
        passwordless: true

platforms:
  - name: centos-7
  - name: debian-8
  - name: debian-9
  - name: fedora-27
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
    - recipe[test::system]
    - recipe[test::security]
  - name: cloud
    run_list:
    - recipe[test::cloud]
  - name: email
    run_list:
    - recipe[test::email]
  - name: multimedia
    run_list:
    - recipe[test::multimedia]
  - name: web
    run_list:
    - recipe[test::web]
