---
driver:
  name: vagrant
  use_sudo: false
  cachier: true
  customize:
    memory: 4096

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.9.41
  log_level: info
  environments_path: test/integration/environments
  data_bags_path: test/fixtures/data_bags
  attributes:
    openssh:
      server:
        permit_root_login: 'yes'
    authorization:
      sudo:
        users: ['vagrant']
        passwordless: true

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: ubuntu-16.04
    run_list:
      - recipe[apt]

suites:
  - name: default
    run_list:
    - recipe[test::default]
  - name: cloud
    run_list:
    - recipe[test::cloud]
  - name: email
    run_list:
    - recipe[test::email]
  - name: multimedia
    run_list:
    - recipe[test::multimedia]
  - name: web
    run_list:
    - recipe[test::web]
