sudo: false
dist: trusty
language: ruby
rvm:
  - 2.3.1

cache:
  bundler: true
  directories:
    - $HOME/.berkshelf/
    - $HOME/.gem/

before_install: gem update --system && gem install bundler --no-document
bundler_args: --without development plugins

env:
  global:
  - TRAVIS=1 CI=1 COVERAGE=1

gemfile:
  - Gemfile

script: bundle exec rake ci
