sudo: required
services: docker
dist: trusty
language: ruby
rvm: 2.3.1

cache:
  bundler: true
  directories:
    - $HOME/.berkshelf/
    - $HOME/.gem/

env:
  matrix:
  - TEST="style:all"
  - TEST="unit"
  - TEST="integration:docker[default-ubuntu-1404]"
  - TEST="integration:docker[cloud-ubuntu-1404]"
  - TEST="integration:docker[email-ubuntu-1404]"
  - TEST="integration:docker[multimedia-ubuntu-1404]"
  - TEST="integration:docker[web-ubuntu-1404]"

matrix:
  fast_finish: true

before_install:
  - curl -L https://www.getchef.com/chef/install.sh | sudo bash -s -- -P chefdk -v 0.18.30
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"

install:
  - chef exec bundle install --jobs=3 --retry=3 --without='development plugins'

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - chef --version
  - berks --version
  - foodcritic --version

script:
  - travis_retry chef exec bundle exec rake ${TEST}

after_failure:
  - cat docker_daemon.log
