sudo: required
services: docker
dist: trusty
language: ruby
rvm: 2.3.6

addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
      - chefdk

cache:
  directories:
    - $HOME/.berkshelf/
    - cookbooks/
    - berks-cookbooks/

env:
  - TEST=default-centos-6
  - TEST=default-centos-7
  - TEST=default-debian-8
  - TEST=default-debian-9
  - TEST=default-ubuntu-1404
  - TEST=default-ubuntu-1604
  - TEST=cloud-centos-6
  - TEST=cloud-centos-7
  - TEST=cloud-debian-8
  - TEST=cloud-debian-9
  - TEST=cloud-ubuntu-1404
  - TEST=cloud-ubuntu-1604
  - TEST=email-centos-6
  - TEST=email-centos-7
  - TEST=email-debian-8
  - TEST=email-debian-9
  - TEST=email-ubuntu-1404
  - TEST=email-ubuntu-1604
  - TEST=multimedia-centos-6
  - TEST=multimedia-centos-7
  - TEST=multimedia-debian-8
  - TEST=multimedia-debian-9
  - TEST=multimedia-ubuntu-1404
  - TEST=multimedia-ubuntu-1604
  - TEST=web-centos-6
  - TEST=web-centos-7
  - TEST=web-debian-8
  - TEST=web-debian-9
  - TEST=web-ubuntu-1404
  - TEST=web-ubuntu-1604

before_script:
  - sudo iptables -L DOCKER || ( echo 'DOCKER iptables chain missing' ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/bin/chef --version
  - /opt/chefdk/bin/cookstyle --version
  - /opt/chefdk/bin/foodcritic --version

script:
  - KITCHEN_LOCAL_YAML=.kitchen.dokken.yml /opt/chefdk/bin/kitchen verify ${TEST}

matrix:
  fast_finish: true
  include:
    - script:
      - /opt/chefdk/bin/chef exec delivery local all
      env: UNIT_AND_LINT=1
  allow_failures:
    env:
    - TEST=default-centos-6
    - TEST=default-debian-8
    - TEST=cloud-centos-6
    - TEST=cloud-centos-7
    - TEST=cloud-debian-8
    - TEST=cloud-debian-9
    - TEST=email-centos-6
    - TEST=email-centos-7
    - TEST=email-debian-8
    - TEST=email-debian-9
    - TEST=multimedia-centos-6
    - TEST=multimedia-centos-7
    - TEST=multimedia-debian-8
    - TEST=multimedia-debian-9
    - TEST=web-centos-6
    - TEST=web-centos-7
    - TEST=web-debian-8
    - TEST=web-debian-9
    
after_failure:
  - cat docker_daemon.log
