sudo: required
services: docker
dist: trusty
language: ruby
rvm: 2.3.6

cache:
  bundler: true
  directories:
    - $HOME/.berkshelf/
    - $HOME/.gem/

env:
  matrix:
  - TEST="style:all"
  - TEST="unit"
  - TEST="integration:docker[default-ubuntu-1404]"
  - TEST="integration:docker[cloud-ubuntu-1404]"
  - TEST="integration:docker[email-ubuntu-1404]"
  - TEST="integration:docker[multimedia-ubuntu-1404]"
  - TEST="integration:docker[web-ubuntu-1404]"

matrix:
  fast_finish: true

before_install:
  - gem install bundler
  - bundle install

install:
  - bundle install --jobs=3 --retry=3 --without='development plugins'

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - chef --version
  - berks --version
  - foodcritic --version

script:
  - travis_retry bundle exec rake ${TEST}

after_failure:
  - cat docker_daemon.log
