sudo: required
services: docker
dist: trusty
language: ruby
rvm: 2.3.1

cache:
  bundler: true
  directories:
    - $HOME/.berkshelf/
    - $HOME/.gem/

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

env:
  global:
  - TRAVIS=1 CI=1 COVERAGE=1
  matrix:
  - INSTANCE=default-ubuntu-1404
  - INSTANCE=default-ubuntu-1604
  # - INSTANCE=default-debian-7.8

matrix:
  fast_finish: true
  include:
  - script:
    - travis_retry bundle exec rake style:all
    - travis_retry bundle exec rake test:unit

before_install:
  - curl -L https://www.getchef.com/chef/install.sh | sudo bash -s -- -P chefdk -v 0.18.30

install:
  - chef exec bundle install

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/berks --version
  - /opt/chefdk/embedded/bin/foodcritic --version

script:
  - chef exec bundle exec kitchen verify ${INSTANCE}

after_failure:
  - cat docker_daemon.log
